my_blog/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name='posts'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls',namespace='posts')),

]

if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^(?P<id>\d+)/$',views.detail,name="detail"),
    url(r'^create/$',views.post_create,name="create"),
    url(r'^(?P<id>\d+)/update/$',views.post_update,name="update"),
    url(r'^(?P<id>\d+)/delete/$',views.post_delete,name="delete"),
]

posts/models.py
from __future__ import unicode_literals

from django.db import models
# Create your models here.


class Post(models.Model):
	title=models.CharField(max_length=120)
	image=models.FileField(null=True,blank=True)
	content=models.TextField()
	updated=models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp=models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.title

posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=["title","image","content"]

posts/views.py
from django.http import HttpResponse 
from django.shortcuts import render,get_object_or_404,redirect
from models import Post
from forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def post_create(request):
	form=PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
	context={ "form":form }
	return render(request,"my_blog/post_create.html",context)

def post_update(request,id=None):
	instance=get_object_or_404(Post,id=id)
	form=PostForm(request.POST or None,request.FILES or None,instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
	context={ "form":form,
			  "title":instance.title,
			  "instance":instance }

	return render(request,"my_blog/post_create.html",context)

def post_delete(request,id):
	form=PostForm(request.POST or None)
	instance=get_object_or_404(Post,id=id)
	instance.delete()
	return redirect("posts:index")

def index(request):
	lists=Post.objects.all().order_by("-timestamp")
	paginator = Paginator(lists, 10) # Show 25 lists per page
	page = request.GET.get('page')
	try:
		lists = paginator.page(page)
	except PageNotAnInteger:
        # If page is not an integer, deliver first page.
		lists = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
		lists = paginator.page(paginator.num_pages)
	
	return render(request,"my_blog/index.html",{'lists':lists})

def detail(request,id):
	lists=Post.objects.get(pk=id)
	return render(request,"my_blog/detail.html",{'lists':lists})

posts/templates/my_blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Blog</title>
		<title>blog</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->

	<link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
	<div class="container">
		{% block content %}{% endblock content%}
	</div>
</body>
</html>

posts/templates/my_blog/detail.html
{% extends 'my_blog/base.html' %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3">
	{% if lists.image %}
		<img src="{{ lists.image.url }}" class="img-responsive">
	{% endif %}
	<h3>{{ lists.title }}</h3>
	{{ lists.content|linebreaks }}
	{{ lists.updated }} <br/>
<div>
{% endblock content%}

posts/templates/my_blog/index.html
{% extends 'my_blog/base.html' %}

{% block content %}	
<div class="col-sm-8 col-sm-offset-2">
	<h1>MyBlog</h1>
	{% for lt in lists %}
		<div class="row">
		  <div class="col-sm-12">
		    <div class="thumbnail">
		      {% if lt.image%}
		      <img src="{{ lt.image.url }}" class="img-responsive">
		      {% endif %}
		      <!img src="..." alt="...">
		      <div class="caption">
		        <h3><a href="{% url 'posts:detail' lt.id %}">{{ lt.title}}</a><small>  {{ lt.timestamp|timesince }} ago</small></h3>
		        <p>{{ lt.content|linebreaks|truncatechars:120 }}</p>
		        <p><a href="{% url 'posts:detail' lt.id %}" class="btn btn-primary" role="button">View</a></p>
		      </div>
		    </div>
		  </div>
		
	
</div>

<div class="pagination">
    <span class="step-links">
        {% if lists.has_previous %}
            <a href="?page={{ lists.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ lists.number }} of {{ lists.paginator.num_pages }}.
        </span>

        {% if lists.has_next %}
            <a href="?page={{ lists.next_page_number }}">next</a>
        {% endif %}
    </span>
</div> 
	{% endfor %}
{% endblock %}

posts/templates/my_blog/post_create.html
{% extends "my_blog/base.html" %}


{% block content%}
	<div class="col-sm-8 col-sm-offset-2"">
		<h1>Form</h1>
		<form method="POST" action="" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p}}
			<input type="submit" Value="Create A post">
		</form>
	</div>
{% endblock %}